### ISSUE TITLE
feedback: Questions for the text

### ISSUE THREAD

**Issue by obonhamcarter** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-solisa986#2]
Hi Adriana,

Below are the questions from your committee that you are to address in your document's text. Please let me know the page numbers on which I can find your responses. If you have any questions, please do not hesitate to let me know. 

Questions from Dr. Ormiston:

1.) If possible, please provide more details about the results of your regression (training) models. This would include communicating your regression coefficients and p-values and evaluating whether your results are sensible. If the regression is not sensible, explain the ramifications (is this a garbage in, garbage out model?). If providing details about your regression is not possible, explain why in sufficient (and layman's) terms. And since it is somewhat unclear in the paper, if your regression training models only included one independent (X) variable, explain how omitted variable bias (discussed in ECON 440) should make us concerned about the validity of the regression model. In general, the economics/regression angle in your paper needs more clarity as this is a double-major comp; if this cannot be provided, then you need to explain why and how this may limit your paper.

2.) There is an inconsistency that needs to be smoothed out. In your introduction, you write, "it can be inferred that past research has not focused on the overall features of movies that can influence their success" but in the literature review, you describe numerous papers that focus on features that affect movie success and then write that in the "most recent ten years, and the literature on the economics of movies has fully developed during this time." Effectively, you start by identifying a research gap as a motivation for your paper, but your literature review infers that no such gap exists. This is just a matter of cleaning up this inconsistency as it is at the heart of the paper.

3.) You mentioned that Pojan (2017) did something similar to your work. Can you briefly describe how your project builds off of, extends, or betters what Pojan did? It was left unclear and establishing the value of your work vis-a-vis prior efforts would be valuable.

Questions from Dr. Bonham-Carter:

Q 1: What kinds of bias exist in data for projects similar to this one? What bias exists in the data of this particular project? How did this bias get into the data? How could it be detected as an early part of the analysis? Discuss the damage that this bias could do to the predictive power of the project?

Q 2: What is a major weakness in using statistical analysis for the data of this project? Discuss the weakness and speculate on how to overcome such a weakness. 

Q 3: An example for the discussion. A film is about to be made which will be directed by a largely unknown director. The film is set to star a well-known actor who has been in three recent films which were very successful, but also has been in two projects which were either cancelled early in production, or did poorly at the box-office. The proposed budget for this film is known, as well as the reaction to several other films of similar themes. While you cannot know for certain, you want to use your dashboard to predict some of the success of this new film.

Use the above example to describe what kinds of data would be necessary, and which methods from the project's dashboard would be most appropriate to use for analysis in predicting box office success (i.e., high ticket sales).

**Comment by solisa986** [comment]
1. Found in the Data Analysis section of the Methodology chapter
2. Found in the first paragraph of the Motivation section in the introduction chapter
3. Found in the second paragraph of the 'Past Areas of Research and Knowledge Gap' section in the introduction chapter
4. answered in the explanation for #1 
5. found in the second paragraph of the 'Challenges to Proposed Research' in the introduction chapter
6. unable to add this in as my dashboard does not accept new movie data (new movies), only new data on pre-existing movies
